name: Qualys WAS Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  qualys-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

     - name: Qualys GitHub actions for Web Application Scanning
        # Change v2.0.0 back to v1.2.1
        uses: Qualys/github-action-qwas@v1.2.1
        with:
          QUALYS_USERNAME: ${{ vars.QUALYS_USERNAME }}
          QUALYS_PASSWORD: ${{ secrets.QUALYS_PASSWORD }}
          API_SERVER: ${{ vars.API_SERVER }}
          SCAN_NAME: ${{ vars.SCAN_NAME }}
          SCAN_TYPE: ${{ vars.SCAN_TYPE }}
          WEBAPP_ID: ${{ vars.WEBAPP_ID }}
